Updates SDG install instructions.

diff --git a/sdg-tunnel-start b/sdg-tunnel-start
--- a/sdg-tunnel-start
+++ b/sdg-tunnel-start
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ ! -f ~/.ssh/id_rsa ]; then
+    echo 'Creating private key for the first time...'
+    cat /dev/zero | ssh-keygen -q -N ""
+fi
+
 ssh -q -oBatchMode=yes pc "exit 0"
 
 if [ $? -ne 0 ]; then
@@ -26,9 +31,11 @@ nameserver 8.8.8.8
 nameserver 8.8.4.4
 EOF
 
-sv status /opt/sdg/tunnel-service 2>/dev/null
+which sv >/dev/null || { echo 'error: first install an updated busybox with runit'; exit 1; }
+
+sv status /opt/sdg/tunnel-service >/dev/null 2>&1
 if [ $? -ne 0 ]; then
     runsv /opt/sdg/tunnel-service >/dev/null 2>&1 &
 fi
 sv up /opt/sdg/tunnel-service
-echo 'tunnelling service started.'
+echo 'tcp tunnelling service started.'
