Removes installation step from install-solo-utils

diff --git a/tools/solo-utils/solo-utils-install-runit b/tools/solo-utils/solo-utils-install-runit
--- a/tools/solo-utils/solo-utils-install-runit
+++ b/tools/solo-utils/solo-utils-install-runit
@@ -3,12 +3,28 @@
 # This script will install runit as a process spawned by /etc/inittab
 # to monitor services under /etc/solo-services under runlevel 4
 
+need() {
+    for var in "$@"; do
+        which "$var" >/dev/null
+        if [ $? != 0 ]; then
+            return 1
+        fi
+    done
+}
+
+need "sv" "glit" || {
+    echo 'error: missing packages. Please run:'
+    echo '   solo-utils tunnel-start'
+    echo '   smart reinstall busybox'
+    exit 1
+}
+
 # This function ensures that a line exists in a given file.
 # If it doesn't, it adds it.
 lineinfile () {
-	FILE=$1
-	LINE=$2
-	grep -q "$LINE" "$FILE" || echo "$LINE" >> "$FILE"
+    FILE=$1
+    LINE=$2
+    grep -q "$LINE" "$FILE" || echo "$LINE" >> "$FILE"
 }
 
 # First create the directory where our services will live.
